"""Suzie Doctor App package."""

APP_VERSION = "0.2.51-dev"
PROTOCOL_PACK_VERSION = "0.1.4-dev"
BRIDGE_VERSION = "0.2.5-dev"

SUITE_VERSION = "0.1.5-dev"
CONNECTOR_VERSION = "0.1.3-dev"
CONNECTOR_INTERFACE_VERSION = 1
CONNECTOR_SCHEMA_VERSION = 1
SKILL_VERSION = "0.1.5-dev"
SKILL_SCHEMA_VERSION = 1
PROTOCOL_CARD_SCHEMA_VERSION = 1
PROTOCOL_PRIMITIVE_SET_VERSION = 3
DOCTOR_SERVER_API_VERSION = "v1"
